server {
    # Nginx lắng nghe ở cổng 3000 như yêu cầu của đề bài
    listen 3000;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Cấu hình fallback cho SPA Routing
        try_files $uri $uri/ /index.html;
    }

    # Trang lỗi 50x
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
